package demo.example.com.chineseuniversitystudentsonline;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import demo.example.com.chineseuniversitystudentsonline.Entiy.MyTab;

import demo.example.com.chineseuniversitystudentsonline.MyTabDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myTabDaoConfig;

    private final MyTabDao myTabDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myTabDaoConfig = daoConfigMap.get(MyTabDao.class).clone();
        myTabDaoConfig.initIdentityScope(type);

        myTabDao = new MyTabDao(myTabDaoConfig, this);

        registerDao(MyTab.class, myTabDao);
    }
    
    public void clear() {
        myTabDaoConfig.clearIdentityScope();
    }

    public MyTabDao getMyTabDao() {
        return myTabDao;
    }

}
